services:

  postgres:
    image: postgres:17
    container_name: bankflow-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: bankflow
      POSTGRES_USER: bankflow
      POSTGRES_PASSWORD: bankflow_dev_password

    ports:
      - "5434:5432"

    volumes:
      - bankflow_postgres_data:/var/lib/postgresql/data

volumes:
  bankflow_postgres_data: