spring.application.name=customer-service

server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5434/bankflow
spring.datasource.username=bankflow
spring.datasource.password=bankflow_dev_password

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

management.endpoints.web.exposure.include=health,info