spring.application.name=core-banking-service

server.port=8082

spring.datasource.url=jdbc:postgresql://localhost:5434/bankflow
spring.datasource.username=bankflow
spring.datasource.password=bankflow_dev_password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

management.endpoints.web.exposure.include=health,info